### ISSUE TITLE
Remove node modules from the project, add to gitignore.

### ISSUE THREAD

**Issue by GustavoRSSilva** [Lightning-Family/lightning.family#2]
Node modules is a file auto generated by the command yarn (or npm install).
Adding it to the .gitignore with reduce the project size. Pretty standard to ignore this folder.

more info: https://www.chaseadams.io/2015/07/my-gitignore-conventions/

It would make it easy to clone the project and the changes would be more precise (would not see libraries override).

**Comment by CarlosRoldanx** [comment]
Absolutely! 
Thanks for the update, feel free to send a PR or I can do it automatically
